name: Feature request
description: Suggest a feature
labels: ["enhancement"]
title: "Feat: "
body:
    - type: markdown
      attributes:
          value: |
              Please ensure that the feature has not already been requested in the issue tracker.
    - type: textarea
      attributes:
          label: Describe the feature you would like
          description:
              Please also describe your goals for the feature. What problems it solves, how it would
              be used, etc.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Additional context
          description: Add any other context to the feature (screenshots, resources, etc.)
